name: Acceptance

on:
  pull_request:
    branches: [main]
    paths: ["**.go", "go.mod", "go.sum", "docker/**", ".github/workflows/testacc.yaml"]
  workflow_call:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_wrapper: false
      - name: Disposable AdGuard Home acceptance tests
        run: make testacc
